### ISSUE TITLE
Different result for pos tagging if using tokens.out and printTokens functions

### ISSUE THREAD

**Issue by moskaliukua** [winkjs/wink-nlp#140]
Hi. for some reason. In sentence **They both give you a nice dashboard**
I recieve different results in doc.printTokens() and tokens out(its.lemma) for pos tagging
regarding verb **give** which is correctly identified in printTokens function **VERB** and incorectly if using tokens.out function **NOUN**
```
import winkNLP from 'wink-nlp';
import model from 'wink-eng-lite-web-model';

const nlp = winkNLP(model);
const its = nlp.its;

const sentence = 'They both give you a nice dashboard';
const doc = nlp.readDoc(sentence);
doc.tokens().each((item) => {
  console.log(item.out(its.lemma), item.out(its.pos));
});
doc.printTokens();


they PRON
both DET
give NOUN - should be the VERB. incorrect POS tagging
you PRON
a DET
nice ADJ
dashboard NOUN


token      p-spaces   prefix  suffix  shape   case    nerHint type     normal/pos
———————————————————————————————————————————————————————————————————————————————————————
They              0   Th      hey     Xxxx    3       0       word     they / PRON
both              1   bo      oth     xxxx    1       0       word     both / DET
give              1   gi      ive     xxxx    1       0       word     give / VERB - correct POS tagging
you               1   yo      you     xxx     1       0       word     you / PRON
a                 1   a       a       x       1       0       word     a / DET
nice              1   ni      ice     xxxx    1       0       word     nice / ADJ
dashboard         1   da      ard     xxxx    1       0       word     dashboard / NOUN
```
versions of packages:
"wink-eng-lite-web-model": "^1.8.0",
"wink-nlp": "^2.3.0",

**Comment by rachnachakraborty** [comment]
Hi @moskaliukua 

The `printTokens()` function outputs the default properties of a token. The **pos** value represents the most likely part of speech for the lexeme. However, during POS tagging, the part of speech might change due to state machine transitions. As a result, the outputs from `tokens().out()` may not always match those from `printTokens()`. You can observe this by testing with a sentence like “A bear crossed the road. I will bear your expenses.”

Regarding your observation, you’re correct that `give` is being incorrectly tagged. The issue arises because `both` is consistently treated as a DET, and a DET followed by a VERB is triggering a transition that reclassifies `give` as a NOUN. In our dataset, we didn’t encounter `both` functioning as an ADV, and give can indeed be a NOUN as well.

Hope it clarifies.

Best,
Rachna
